version: '3.2'
services:
  # start service for redmine with plugin
  # 1. Build
  # $ docker-compose build --force-rm --no-cache
  #   or
  # $ docker build --build-arg=COMMIT=$(git rev-parse --short HEAD) \
  #    --build-arg=BRANCH=$(git name-rev --name-only HEAD) \
  #    -t akiko/redmine_banner:latest .
  #
  # 2. $ docker-compose up -d web
  #
  #
  web:
    build:
      context: .
    image: akiko/redmine_banner:latest
    container_name: redmine_sqlite3
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app/redmine/plugins/redmine_banner
    ports:
      - "3000:3000"
